---
build:
  image: docker-registry.fusic.co.jp:5000/sadakata/centos7
  privileged: true
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  commands:
    - mkdir -p /var/run/postgresql && chown -R postgres /var/run/postgresql
    - su -l postgres -c "/usr/bin/pg_ctl start -D /var/lib/pgsql/data -s -o '-p 5432' -w -t 300"
    - psql -U postgres -c 'create database test_cake;'
    - php composer.phar install
    - ./app/Console/cake test app Model/Post

