---
build:
  image: sadapon2008/drone-centos6-remi-php55-pgdg-postgresql93
  commands:
    - su -l postgres -c "/usr/pgsql-9.3/bin/pg_ctl start -D /var/lib/pgsql/9.3/data -s -o '-p 5432' -w -t 300"
    - psql -U postgres -c 'create database test_cake;'
    - source /etc/profile.d/enablephp55.sh
    - php composer.phar install
    - ./app/Console/cake test app Model/Post

